'use client';
import { useState,type FormEvent } from 'react';import { useSearchParams } from 'next/navigation';import { copy,type Locale } from '@/lib/i18n';
type RequestType='consulting'|'quote'|'demo'|'material'|'factory-talent'|'candidate'|'contact';
const types:RequestType[]=['consulting','quote','demo','material','factory-talent','candidate','contact'];
export function IntakeForm({locale}:{locale:Locale}){const t=copy[locale];const search=useSearchParams();const initial=search.get('type');const [step,setStep]=useState(0);const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const [form,setForm]=useState({type:(types.includes(initial as RequestType)?initial:'consulting') as RequestType,subject:search.get('subject')||'',name:'',email:'',phone:'',company:'',line_type:'',challenge:'',deliverables:'',location:'',experience:'',consent:false});const [file,setFile]=useState<File|null>(null);
function change(key:keyof typeof form,value:string|boolean){setForm(prev=>({...prev,[key]:value}))}
async function submit(event:FormEvent){event.preventDefault();if(step<2){setStep(step+1);return}setStatus('sending');const data=new FormData();Object.entries({...form,locale}).forEach(([key,value])=>data.append(key,String(value)));if(file)data.append('attachment',file);try{const response=await fetch('/api/requests',{method:'POST',body:data});setStatus(response.ok?'success':'error')}catch{setStatus('error')}}
const label=(text:string,field:React.ReactNode)=><label className="block text-sm font-semibold text-slate-700">{text}<div className="mt-2">{field}</div></label>;
if(status==='success')return <div role="status" className="card max-w-3xl p-10 text-xl font-bold text-[#0c526c]">✓ {t.success}</div>;
return <form onSubmit={submit} className="card max-w-3xl p-6 md:p-10"><div className="mb-9 flex gap-2">{[0,1,2].map(n=><span key={n} className={`h-1.5 flex-1 rounded ${n<=step?'bg-[#0c526c]':'bg-slate-200'}`}/>)}</div><div className="grid gap-6 md:grid-cols-2">{step===0&&<>{label(t.type,<select className="field" value={form.type} onChange={e=>change('type',e.target.value)}>{types.map(type=><option key={type} value={type}>{type}</option>)}</select>)}{label(t.line,<select className="field" value={form.line_type} onChange={e=>change('line_type',e.target.value)}><option value="">—</option>{['Pipe Extrusion','Injection','Compounding','Blown Film','Other'].map(v=><option key={v}>{v}</option>)}</select>)}{label(t.company,<input className="field" value={form.company} maxLength={160} onChange={e=>change('company',e.target.value)}/>)}{label(t.location,<input className="field" value={form.location} maxLength={160} onChange={e=>change('location',e.target.value)}/>)}</>}{step===1&&<>{label(t.challenge,<textarea className="field min-h-32" required value={form.challenge} maxLength={3000} onChange={e=>change('challenge',e.target.value)}/>)}{label(t.expected,<textarea className="field min-h-32" value={form.deliverables} maxLength={2000} onChange={e=>change('deliverables',e.target.value)}/>)}{label(t.experience,<input className="field" value={form.experience} maxLength={300} onChange={e=>change('experience',e.target.value)}/>)}{label(locale==='ar'?'مرفق PDF اختياري، حتى 2 MB':'Optional PDF attachment, up to 2 MB',<input className="field" type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/>)}</>}{step===2&&<>{label(t.name,<input className="field" required value={form.name} maxLength={120} onChange={e=>change('name',e.target.value)}/>)}{label(t.email,<input className="field" required type="email" value={form.email} maxLength={200} onChange={e=>change('email',e.target.value)}/>)}{label(t.phone,<input className="field" type="tel" value={form.phone} maxLength={40} onChange={e=>change('phone',e.target.value)}/>)}<label className="flex items-start gap-3 text-sm md:col-span-2"><input type="checkbox" required checked={form.consent} onChange={e=>change('consent',e.target.checked)}/><span>{t.consent}</span></label></>}</div>{status==='error'&&<p role="alert" className="mt-5 text-red-700">{t.error}</p>}<div className="mt-9 flex gap-3">{step>0&&<button type="button" className="btn-outline" onClick={()=>setStep(step-1)}>{t.back}</button>}<button disabled={status==='sending'} className="btn-primary disabled:opacity-50" type="submit">{step===2?t.send:t.next} ↗</button></div></form>}
