INSERT INTO content (kind,slug,title_ar,title_en,summary_ar,summary_en,body_ar,body_en,category_ar,category_en,status) VALUES
('service','pipe-extrusion','تشخيص وتحسين بثق المواسير','Pipe extrusion diagnostics and optimization','مراجعة مشكلات التشغيل وثبات العملية في خطوط PVC وCPVC وHDPE.','Investigate operating issues and process stability on PVC, CPVC, and HDPE pipe lines.','نراجع بيانات الخط والخامة والمنتج ومؤشرات الجودة المتاحة، ثم نتفق على نطاق التشخيص والتجارب والمخرجات قبل بدء العمل. يتطلب تقييم الحالة سجلات التشغيل، ومواصفات المنتج، ونتائج الفحص، ووصف المشكلة.','We review available line, material, product, and quality data, then agree on diagnostic scope, trials, and deliverables. Relevant inputs include operating records, product specifications, test results, and a description of the issue.','البثق','Extrusion','published'),
('service','formulation-review','مراجعة الخلطات والإضافات','Formulation and additives review','تقييم بدائل الخامات وتناسق الإضافات والتأثير المحتمل على التشغيل والمنتج.','Evaluate material alternatives and additive balance for process and product requirements.','نراجع التركيبة الحالية والبيانات الفنية للمواد والنتائج المطلوبة. أي تعديل مقترح يحتاج تجربة تشغيل واختبارات قبل اعتماده. تشمل المخرجات المحتملة خطة مقارنة وتجارب ونقاط متابعة.','We review the existing formulation, material technical data, and target properties. Any proposed changes need plant trials and testing before approval. Deliverables can include a comparison plan, trial plan, and monitoring points.','الخلطات','Formulation','published'),
('service','scrap-cost','تحليل الهالك وتكلفة المواد','Scrap and material cost analysis','تحليل استهلاك المواد والفاقد لتحديد أسباب الانحراف وفرص التحسين.','Analyze material usage and losses to identify variance drivers and improvement options.','تبدأ المراجعة ببيانات الإنتاج والمواد المرتجعة وأوزان المنتجات وأسعار المواد المتاحة. نحدد نطاق الحسابات والتقرير بعد مراجعة جودة البيانات.','The review starts with production records, returns, product weights, and available material prices. Calculation and report scope are agreed after checking data quality.','التكاليف','Cost analysis','published'),
('service','production-planning','تخطيط الإنتاج وتوزيع الخطوط','Production planning and line allocation','توزيع الطلبات على الخطوط وفق قدراتها ومعدلاتها والقيود التشغيلية.','Allocate orders to production lines using capacities, rates, and operating constraints.','نراجع خطوط الإنتاج والمنتجات والطلبات والمعدلات الفعلية وأوقات التغيير. يحدد عرض الخدمة شكل خطة الإنتاج والتقارير المطلوبة.','We review line capabilities, product mix, orders, actual rates, and changeover times. The proposal defines the production plan and reporting outputs.','التخطيط','Planning','published'),
('service','industrial-trials','إدارة التجارب والتشغيل الأولي','Industrial trials and commissioning support','تحديد هدف التجربة وتوثيق ظروف التشغيل والنتائج ومعايير القرار.','Define trial objectives and document process settings, results, and decision criteria.','يمكن إعداد بطاقة تجربة وخطة أخذ عينات وسجل للإعدادات والنتائج. اعتماد أي خامة أو إعداد يبقى مشروطًا بنتائج الفحص ومتطلبات المصنع.','Outputs may include a trial sheet, sampling plan, and settings and results log. Approval remains subject to testing and plant requirements.','التجارب','Trials','published'),
('service','quality-records','مراجعة إجراءات الجودة والسجلات','Quality procedures and production records','تنظيم نماذج الفحص والمتابعة الفنية وربطها بقرارات التشغيل.','Structure inspection and technical records around operational decisions.','نراجع نماذج المتابعة الحالية ونقاط القياس ودورية التسجيل والتصعيد. تُحدد النماذج النهائية وفق نطاق المشروع.','We review existing logs, measurement points, frequency, and escalation. Final templates depend on the agreed scope.','الجودة','Quality','published'),
('material','material-validation','كيف تقيّم خامة بديلة؟','How to evaluate an alternative material','خطوات عامة للمقارنة قبل اتخاذ قرار تجربة خامة جديدة.','A general comparison approach before trialing a new material.','ابدأ بمواصفة المنتج وطريقة التشغيل، ثم قارن نشرات البيانات الفنية وشهادات التحليل وحدود التباين بين الشحنات. ضع خطة تجربة تراقب التشغيل وجودة المنتج والتكلفة والتوافر. لا تعتمد البديل من مقارنة السعر فقط.','Start with the product specification and process, then compare technical data sheets, certificates of analysis, and batch variation. Plan a trial covering processing, product quality, cost, and supply. Price comparison alone does not approve a substitute.','تقييم البدائل','Alternative validation','published'),
('insight','trial-records','ما الذي يجب تسجيله في تجربة إنتاج؟','What should a production trial record?','سجل واضح يساعد الفريق على تفسير النتيجة وإعادة التجربة.','A clear log helps the team interpret and reproduce trial results.','دوّن هدف التجربة، كود المادة والدفعة، إعدادات الخط الفعلية، المنتج، زمن الاستقرار، العينات، نتائج الفحص، والملاحظات أثناء التشغيل. افصل بين ما تمت ملاحظته وما تم استنتاجه، وحدد معيار القبول قبل بدء التجربة.','Record the objective, material and batch IDs, actual line settings, product, stabilization time, samples, test results, and observations. Keep observations separate from conclusions, and define acceptance criteria before starting.','التجارب','Trials','published')
ON CONFLICT (kind,slug) DO NOTHING;
